### ISSUE TITLE
Cannot advance to next step in tutorial

### ISSUE THREAD

**Issue by lucidbard** [codespaces-contrib/codeswing#23]
Currently the posted message doesn't appear to get sent and the buttons in the header don't adjust the current tutorial state. In the test, I'm opening a codeswing in a child directory with the correct codeswing.json, but the tree view is showing the subdirectories.
![image](https://user-images.githubusercontent.com/2390806/105789913-40dac180-5f51-11eb-858b-f55576de29da.png)

It seems like the posted message is getting stopped in an iframe that is sitting between VS Code and the sandbox that runs the tutorial advance header. Perhaps it should be forwarded?

**Comment by lostintangent** [comment]
Hey! Thanks for reporting this. Yeah it seems like there's a bug in the tutorial navigation header, so I'll take a look.

If you don't mind sharing, I'd love to hear what you have in mind for tutorials. I built that as a bit of an experimental feature, and I wasn't actually aware of anyone using them 😁 That said, I'm keen to learn more about if they're useful and how we could improve the overall experience.

**Comment by lucidbard** [comment]
Thanks for replying so quickly!

I am actually teaching a course on React / React Native at UCF (among other courses). 

I was going to take a look later today at possibly submitting a pull request, as I'm very interested in providing my students a tutorial that is both in-editor and not a video.

I'm also working on a larger project that includes a content management frontend for canvas within a VS Code extension, which also includes integrated unit tests / etc for students. The student-facing extension would incorporate unit testing to assess whether a step of an interactive tutorial has been satisfied before advancing, while a server could handle additional unit tests.

It would be great if I could tie jest test results to the progression of the tutorial, as that way it could be integrated into more of an assignment.

I ran across this extension while I was experimenting with doing a more "typing demo" style approach, putting timed edits into the buffer. That could still work for hints or if a student has attempted the solution a number of times.

Happy to discuss more.

**Comment by lostintangent** [comment]
Just published the fix for this to the marketplace. The issue was exactly as you described 😄  Thanks for reporting this!
