### ISSUE TITLE
[request] - Use "build" shortcut to "Run Swing" if codeswing is open

### ISSUE THREAD

**Issue by jasonwilliams** [codespaces-contrib/codeswing#26]
VSCode has pre-defined shortcuts for build.  This means it's already natural for users to run this when they want to execute a script or start building something they've put together. It's a good match for CodeSwing to bind this to "Run Swing".

On MacOS its:
```json
{
  "key": "shift+cmd+b",
  "command": "workbench.action.tasks.build"
}
```

It would be good to make use of this when inside a codeswing to run the code (or hit "run swing" effectively). As users are already familiar with this it would be more intuitive (rather than making a new shortcut).
In order to not be disruptive to existing workflows it can only be active when a codeswing is open, this way it's only overridden when someone is actively using codeswing and not all the time.

**Comment by lostintangent** [comment]
That's an awesome suggestion! I should be able to slip this in this week 👍

**Comment by lostintangent** [comment]
This has been addressed and will be released in an update this afternoon 👍

**Comment by jasonwilliams** [comment]
Looking forward
Thanks @lostintangent !

**Comment by lostintangent** [comment]
This has now been published! Let me know if you run into any issues. Thanks again for the feedback 🙌
