### ISSUE TITLE
Allow saving a scratch swing

### ISSUE THREAD

**Issue by lostintangent** [codespaces-contrib/codeswing#3]

**Comment by radiantly** [comment]
Firstly - this is a fantastic extension! Great work!

Just an idea, but maybe there could be a config option where all temporary swings are saved in a given directory. This would really help out in scenarios where you want to reference something you tried a bit back, but didn't really save as a separate swing. Each temp swing could be saved in a sub-directory with the date/time as dir name.

**Comment by lostintangent** [comment]
Hey! I think that's a great idea 💡 So maybe we could introduce two new settings:

1. Directory for storing temp swings - By default, this could be a folder within the temp directory (e.g. $TMPDIR/codeswing), but it would allow users to specify their own custom location

2. Format string for naming the temp swings - This would define the naming convention for each temp swing's folder, and by default, could be set to the date and time

**Comment by lostintangent** [comment]
This is now shipped! Scratch swings are now stored in temp storage by default, but you can customize it to use a custom folder 🎉
