### ISSUE TITLE
Publish to Open VSX Registry

### ISSUE THREAD

**Issue by mountainash** [codespaces-contrib/codeswing#33]
I saw the post on [Twitter](https://twitter.com/LostInTangent/status/1361390221489659906) - looks like this could be very helpful. Could this extension please be published to https://open-vsx.org/ aswell as Microsoft's Visual Studio Marketplace (for [easy] use in [VScodium](https://github.com/VSCodium/vscodium))?

**Comment by lostintangent** [comment]
Unfortunately I only have the bandwidth to support VS Code right now (as opposed to other distros), and so I'm going to close this for the time being, and will re-asses it in the future. Thanks for the feedback!
